### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by nuclearthinking** [nuclearthinking/myheroagency#1]
1. Стартовый экран #2 
2. Основной (home) экран #3 
3. Экран заданий #4 
4. Экран сражения #5 
5. Локализация (Ru, Eng) #6 
6. Сохранение прогресса. #7 
7. Возобновление игры #8 
8. Хранение настроек игры #9

**Comment by Izonami** [comment]
В [Бранче](https://github.com/nuclearthinking/myheroagency/tree/firstGameState) сделал пример реализации GameState

Пожелания, предложения принимаются. 
Попозже попробую ещё один вариант в другом бранче

**Comment by nuclearthinking** [comment]
Тоже сделал пример реализации гейм стейт с некоторыми отличиями [тут](https://github.com/nuclearthinking/myheroagency/tree/gsm)
