### ISSUE TITLE
Стартовый экран

### ISSUE THREAD

**Issue by nuclearthinking** [nuclearthinking/myheroagency#2]
Реализовать стартовый экран - экран который видит человек при запуске приложения 
На данном этапе на нём достаточно кнопки начать \ продолжить игру 
И нумерации версии

**Comment by Izonami** [comment]
Попробовал реализовать прототип главного меню в [бранче](https://github.com/nuclearthinking/myheroagency/tree/mainMenu)

столкнулся с проблемами
- [x] Для реализации скинов кнопок нужно подгружать json файл, через Gdx.files.internal некрасиво, надо придумать способ обработки
- [ ] Придумать какую то фабрику для создания кнопок. Пока выглядит как сплошной говнакод
- [x] Скорее всего нужно будет кнопки обернуть в таблицу, что бы при ресайзах не разваливались по экрану

**Comment by nuclearthinking** [comment]
Читал документацию по ассет менеджеру, он поддерживает написание кастомных асетов, т.е. можно дописать туда подгрузку JSON файлов

**Comment by nuclearthinking** [comment]
в мастере
