### ISSUE TITLE
Локализация (Ru, Eng)

### ISSUE THREAD

**Issue by nuclearthinking** [nuclearthinking/myheroagency#6]
Реализовать способ  хранения нескольки  локализаций 
получения локализованной строки в зависимости от текущей локализации. 
- [x]  сделать обёртку над механизмом локализации движка
- [x] интегрировать локализацию в стейт машину

**Comment by nuclearthinking** [comment]
https://github.com/libgdx/libgdx/wiki/Internationalization-and-Localization

**Comment by nuclearthinking** [comment]
#12

**Comment by Izonami** [comment]
Стейт машина смерджена, можно на неё натягивать локаль

**Comment by nuclearthinking** [comment]
done
